[
  "/misc/nixpkgs.nix"
  "/misc/extra-arguments.nix"
  "/config/appstream.nix"
  "/services/x11/window-managers/qtile.nix"
  "/services/x11/window-managers/i3.nix"
  "/services/x11/window-managers/exwm.nix"
  "/services/x11/desktop-managers/plasma5.nix"
  "/services/x11/desktop-managers/xfce.nix"
  "/services/networking/znc/options.nix"
  "/services/continuous-integration/hercules-ci-agent/common.nix"
  "/virtualisation/xen-dom0.nix"
  "/virtualisation/podman/default.nix"
  [ "/virtualisation/parallels-guest.nix" ]
  "/virtualisation/openvswitch.nix"
  "/virtualisation/disk-size-option.nix"
  [ "/virtualisation/lxd.nix" ]
  "/virtualisation/libvirtd.nix"
  [ "/virtualisation/hyperv-guest.nix" ]
  [ "/virtualisation/docker.nix" ]
  [ "/tasks/filesystems/zfs.nix" ]
  "/system/boot/systemd.nix"
  [ "/system/boot/luksroot.nix" ]
  "/system/boot/loader/grub/grub.nix"
  [ "/system/boot/initrd-ssh.nix" ]
  "/system/activation/top-level.nix"
  "/services/x11/xserver.nix"
  [ "/services/x11/window-managers/bspwm.nix" ]
  "/services/x11/picom.nix"
  [ "/services/x11/display-managers/slim.nix" ]
  "/services/x11/display-managers/gdm.nix"
  "/services/x11/display-managers/default.nix"
  [ "/services/web-servers/varnish/default.nix" ]
  [ "/services/web-servers/phpfpm/default.nix" ]
  [ "/services/web-servers/nginx/default.nix" ]
  "/services/web-servers/fcgiwrap.nix"
  [ "/services/web-servers/caddy/default.nix" ]
  [ "/services/web-servers/apache-httpd/default.nix" ]
  "/services/web-apps/youtrack.nix"
  [ "/services/web-apps/vikunja.nix" ]
  [ "/services/web-apps/tt-rss.nix" ]
  "/services/web-apps/plausible.nix"
  "/services/web-apps/plantuml-server.nix"
  [ "/services/web-apps/outline.nix" ]
  "/services/web-apps/nextcloud.nix"
  "/services/web-apps/matomo.nix"
  "/services/web-apps/mastodon.nix"
  "/services/web-apps/lemmy.nix"
  "/services/web-apps/keycloak.nix"
  "/services/web-apps/hledger-web.nix"
  "/services/web-apps/hedgedoc.nix"
  "/services/web-apps/bookstack.nix"
  "/services/video/epgstation/default.nix"
  "/services/ttys/getty.nix"
  "/services/system/nix-daemon.nix"
  "/services/system/earlyoom.nix"
  [ "/services/security/usbguard.nix" ]
  "/services/security/tor.nix"
  [ "/services/security/fail2ban.nix" ]
  "/services/security/esdm.nix"
  [ "/services/security/clamav.nix" ]
  [ "/services/security/aesmd.nix" ]
  "/services/search/hound.nix"
  "/services/printing/cupsd.nix"
  "/services/networking/zeronet.nix"
  "/services/networking/wpa_supplicant.nix"
  [ "/services/networking/unifi.nix" ]
  [ "/services/networking/unbound.nix" ]
  "/services/networking/thelounge.nix"
  [ "/services/networking/syncthing.nix" ]
  [ "/services/networking/syncplay.nix" ]
  [ "/services/networking/stubby.nix" ]
  "/services/networking/sslh.nix"
  [ "/services/networking/sniproxy.nix" ]
  "/services/networking/smokeping.nix"
  "/services/networking/privoxy.nix"
  "/services/networking/pdns-recursor.nix"
  [ "/services/networking/openvpn.nix" ]
  "/services/networking/networkmanager.nix"
  "/services/networking/murmur.nix"
  "/services/networking/mtr-exporter.nix"
  "/services/networking/kresd.nix"
  "/services/networking/jitsi-videobridge.nix"
  [ "/services/networking/iodine.nix" ]
  "/services/networking/hostapd.nix"
  "/services/networking/headscale.nix"
  "/services/networking/frr.nix"
  "/services/networking/dnsmasq.nix"
  [ "/services/networking/ddclient.nix" ]
  "/services/networking/bird.nix"
  "/services/networking/aria2.nix"
  "/services/network-filesystems/samba.nix"
  "/services/network-filesystems/rsyncd.nix"
  [ "/services/network-filesystems/netatalk.nix" ]
  [ "/services/network-filesystems/davfs2.nix" ]
  [ "/services/monitoring/zabbix-server.nix" ]
  [ "/services/monitoring/zabbix-proxy.nix" ]
  [ "/services/monitoring/zabbix-agent.nix" ]
  [ "/services/monitoring/vmagent.nix" ]
  "/services/monitoring/rustdesk-server.nix"
  [ "/services/monitoring/prometheus/default.nix" ]
  [ "/services/monitoring/prometheus/alertmanager.nix" ]
  "/services/monitoring/nagios.nix"
  [ "/services/monitoring/graphite.nix" ]
  [ "/services/monitoring/grafana.nix" ]
  "/services/misc/taskserver"
  "/services/misc/tabby.nix"
  "/services/misc/sourcehut"
  "/services/misc/redmine.nix"
  "/services/misc/pykms.nix"
  [ "/services/misc/plex.nix" ]
  [ "/services/misc/parsoid.nix" ]
  [ "/services/misc/packagekit.nix" ]
  "/services/misc/ollama.nix"
  [ "/services/misc/nzbget.nix" ]
  [ "/services/misc/nitter.nix" ]
  [ "/services/misc/gpsd.nix" ]
  "/services/misc/gollum.nix"
  "/services/misc/gitlab.nix"
  "/services/misc/gitea.nix"
  "/services/misc/geoipupdate.nix"
  "/services/misc/forgejo.nix"
  [ "/services/misc/etebase-server.nix" ]
  [ "/services/misc/cfdyndns.nix" ]
  "/services/misc/apache-kafka.nix"
  "/services/matrix/synapse.nix"
  [ "/services/mail/rspamd.nix" ]
  [ "/services/mail/postfix.nix" ]
  "/services/mail/mailman.nix"
  "/services/mail/mailhog.nix"
  "/services/mail/dovecot.nix"
  [ "/services/logging/syslog-ng.nix" ]
  [ "/services/logging/logstash.nix" ]
  "/services/logging/logrotate.nix"
  [ "/services/logging/klogd.nix" ]
  [ "/services/logging/awstats.nix" ]
  "/services/home-automation/zigbee2mqtt.nix"
  "/services/home-automation/home-assistant.nix"
  [ "/services/hardware/keyd.nix" ]
  "/services/hardware/fwupd.nix"
  "/services/hardware/bluetooth.nix"
  "/services/hardware/asusd.nix"
  [ "/services/display-managers/sddm.nix" ]
  "/services/desktops/tumbler.nix"
  "/services/desktops/pipewire/pipewire.nix"
  "/services/desktops/gnome/tinysparql.nix"
  [ "/services/desktops/gnome/gnome-online-miners.nix" ]
  [ "/services/databases/redis.nix" ]
  "/services/databases/postgresql.nix"
  "/services/databases/pgbouncer.nix"
  "/services/databases/neo4j.nix"
  "/services/databases/mysql.nix"
  [ "/services/databases/mongodb.nix" ]
  [ "/services/databases/memcached.nix" ]
  "/services/continuous-integration/gitlab-runner.nix"
  "/services/continuous-integration/github-runner/service.nix"
  "/services/continuous-integration/github-runners.nix"
  "/services/continuous-integration/buildbot/master.nix"
  "/services/computing/slurm/slurm.nix"
  "/services/computing/foldingathome/client.nix"
  "/services/cluster/patroni/default.nix"
  "/services/cluster/kubernetes/kubelet.nix"
  "/services/cluster/kubernetes/default.nix"
  "/services/cluster/kubernetes/controller-manager.nix"
  "/services/cluster/kubernetes/apiserver.nix"
  "/services/cluster/k3s/default.nix"
  [ "/services/backup/tarsnap.nix" ]
  "/services/backup/postgresql-backup.nix"
  "/services/audio/alsa.nix"
  [ "/services/amqp/rabbitmq.nix" ]
  "/security/wrappers/default.nix"
  [ "/security/rngd.nix" ]
  "/security/krb5"
  [ "/security/duosec.nix" ]
  "/security/apparmor.nix"
  "/security/acme"
  [ "/rename.nix" ]
  "/programs/wayland/hyprland.nix"
  [ "/programs/qt5ct.nix" ]
  [ "/programs/oblogout.nix" ]
  [ "/programs/gnupg.nix" ]
  "/programs/clash-verge.nix"
  "/programs/bash/bash.nix"
  [ "/programs/_1password.nix" ]
  [ "/programs/_1password-gui.nix" ]
  "/misc/locate.nix"
  "/misc/documentation.nix"
  "/i18n/input-method/kime.nix"
  [ "/i18n/input-method/fcitx5.nix" ]
  "/hardware/graphics.nix"
  "/hardware/device-tree.nix"
  [ "/config/zram.nix" ]
  "/config/xdg/portal.nix"
  "/config/resolvconf.nix"
  "/config/networking.nix"
  "/config/fonts/packages.nix"
  "/config/fonts/fontconfig.nix"
  "/config/console.nix"
  "/tasks/network-interfaces.nix"
  "/tasks/filesystems/overlayfs.nix"
  "/tasks/filesystems.nix"
  "/system/boot/stage-1.nix"
  "/system/boot/kernel.nix"
  "/system/boot/binfmt.nix"
  "/services/security/authelia.nix"
  "/services/networking/iwd.nix"
  "/services/networking/firewall-iptables.nix"
  "/services/networking/firewall.nix"
  "/services/monitoring/prometheus/exporters.nix"
  "/services/misc/nix-optimise.nix"
  "/services/misc/nix-gc.nix"
  "/services/hardware/udev.nix"
  "/services/display-managers/default.nix"
  "/services/desktops/pipewire/wireplumber.nix"
  "/services/backup/restic.nix"
  "/security/systemd-confinement.nix"
  "/security/sudo.nix"
  "/security/pam.nix"
  "/programs/ssh.nix"
  "/programs/shadow.nix"
  "/programs/nh.nix"
  "/misc/version.nix"
  "/misc/nixpkgs-flake.nix"
  "/misc/nixops-autoluks.nix"
  "/config/users-groups.nix"
  "/config/swap.nix"
  "/config/nsswitch.nix"
  "/config/nix-remote-build.nix"
  "/config/ldso.nix"
  [ "/misc/assertions.nix" ]
  "/tasks/bcache.nix"
  "/system/boot/modprobe.nix"
  [ "/system/activation/bootspec.nix" ]
  "/virtualisation/nixos-containers.nix"
  "/services/networking/netbird.nix"
  "/system/boot/stage-2.nix"
  "/tasks/filesystems/ext.nix"
  "/tasks/filesystems/btrfs.nix"
  "/system/boot/clevis.nix"
  "/services/hardware/amdgpu.nix"
  "/tasks/lvm.nix"
  "/services/system/dbus.nix"
  "/system/boot/systemd/dm-verity.nix"
  [ "/system/boot/systemd/initrd.nix" ]
  "/system/boot/systemd/fido2.nix"
  "/system/boot/systemd/repart.nix"
  "/system/boot/shutdown.nix"
  "/services/misc/graphical-desktop.nix"
  "/config/sysctl.nix"
  "/tasks/cpu-freq.nix"
  "/services/hardware/display.nix"
  [ "/system/boot/loader/efi.nix" ]
  "/system/boot/loader/external/external.nix"
  "/system/boot/loader/systemd-boot/systemd-boot.nix"
  [ "/system/boot/loader/loader.nix" ]
  "/system/boot/tmp.nix"
  "/misc/man-db.nix"
  "/misc/mandoc.nix"
  "/config/shells-environment.nix"
  "/config/system-path.nix"
  "/config/terminfo.nix"
  "/system/boot/timesyncd.nix"
  "/system/boot/systemd/user.nix"
  "/system/boot/systemd/tmpfiles.nix"
  "/system/boot/systemd/oomd.nix"
  "/system/boot/systemd/logind.nix"
  "/system/boot/systemd/journald.nix"
  "/system/boot/systemd/coredump.nix"
  "/system/boot/networkd.nix"
  "/services/system/nscd.nix"
  "/services/networking/modemmanager.nix"
  "/services/misc/uhub.nix"
  "/services/hardware/udisks2.nix"
  "/security/polkit.nix"
  "/security/ca.nix"
  "/programs/zsh/zsh.nix"
  "/programs/nano.nix"
  "/programs/git.nix"
  "/programs/fuse.nix"
  "/programs/dconf.nix"
  "/config/xdg/mime.nix"
  "/config/system-environment.nix"
  "/config/nix-flakes.nix"
  "/config/nix.nix"
  "/config/locale.nix"
  "/config/i18n.nix"
  "/system/etc/etc.nix"
  "/programs/environment.nix"
  "/config/nix-channel.nix"
  "/config/stub-ld.nix"
  "/config/malloc.nix"
  "/programs/xwayland.nix"
  "/config/xdg/sounds.nix"
  "/config/xdg/menus.nix"
  "/config/xdg/icons.nix"
  "/config/xdg/autostart.nix"
  "/services/desktops/gnome/at-spi2-core.nix"
  "/services/accessibility/speechd.nix"
  "/installer/tools/tools.nix"
  "/virtualisation/spice-usb-redirection.nix"
  "/system/boot/kexec.nix"
  "/services/misc/spice-vdagentd.nix"
  "/security/rtkit.nix"
  "/programs/virt-manager.nix"
  "/programs/skim.nix"
  "/programs/less.nix"
  "/programs/command-not-found/command-not-found.nix"
  "/system/activation/activation-script.nix"
  [ "/tasks/encrypted-devices.nix" ]
  [ "/config/fonts/fontdir.nix" ]
  "/services/hardware/amdvlk.nix"
  "/hardware/iosched.nix"
  "/hardware/ckb-next.nix"
  "/hardware/cpu/amd-ryzen-smu.nix"
  "/hardware/cpu/intel-sgx.nix"
  "/hardware/cpu/x86-msr.nix"
  "/hardware/all-firmware.nix"
  "/installer/scan/not-detected.nix"
  "/services/hardware/fancontrol.nix"
  "/hardware/i2c.nix"
  "/hardware/video/intel-gpu-tools.nix"
  "/hardware/libftdi.nix"
  "/hardware/mcelog.nix"
  "/hardware/new-lg4ff.nix"
  "/hardware/nfc-nci.nix"
  "/hardware/openrazer.nix"
  "/hardware/opentabletdriver.nix"
  "/services/hardware/rasdaemon.nix"
  "/hardware/rtl-sdr.nix"
  "/hardware/saleae-logic.nix"
  "/hardware/sata.nix"
  "/hardware/sensor/hddtemp.nix"
  "/services/hardware/tuxedo-rs.nix"
  "/hardware/uni-sync.nix"
  "/hardware/xone.nix"
  "/hardware/xpadneo.nix"
  "/i18n/input-method/default.nix"
  "/misc/ids.nix"
  [ "/misc/lib.nix" ]
  "/virtualisation/podman/network-socket.nix"
  "/services/networking/nat-iptables.nix"
  "/tasks/network-interfaces-scripted.nix"
  "/services/networking/jool.nix"
  [ "/services/networking/nat.nix" ]
  "/services/networking/nm-file-secret-agent.nix"
  [ "/services/networking/nftables.nix" ]
  "/services/networking/openconnect.nix"
  "/config/stevenblack.nix"
  "/services/networking/ucarp.nix"
  [ "/services/networking/wireguard.nix" ]
  "/config/power-management.nix"
  "/programs/adb.nix"
  "/programs/alvr.nix"
  "/programs/amnezia-vpn.nix"
  "/programs/appimage.nix"
  "/programs/bandwhich.nix"
  "/programs/bash/blesh.nix"
  "/programs/bash/bash-completion.nix"
  "/programs/bash/ls-colors.nix"
  "/programs/bash/undistract-me.nix"
  "/config/vte.nix"
  "/programs/bat.nix"
  "/programs/bazecor.nix"
  "/programs/benchexec.nix"
  "/programs/wayland/cardboard.nix"
  "/programs/cfs-zen-tweaks.nix"
  "/programs/coolercontrol.nix"
  "/hardware/corectrl.nix"
  "/programs/cpu-energy-meter.nix"
  "/programs/digitalbitbox/default.nix"
  "/programs/direnv.nix"
  "/programs/dmrconfig.nix"
  "/programs/dublin-traceroute.nix"
  "/programs/envision.nix"
  "/services/desktops/gnome/evolution-data-server.nix"
  "/programs/fcast-receiver.nix"
  "/programs/firefox.nix"
  "/programs/firejail.nix"
  "/programs/fish.nix"
  "/programs/flashprog.nix"
  "/programs/foot"
  "/programs/fzf.nix"
  "/programs/gamemode.nix"
  "/programs/gamescope.nix"
  "/programs/geary.nix"
  "/programs/ghidra.nix"
  "/programs/gnome-disks.nix"
  "/programs/gnome-terminal.nix"
  "/programs/gphoto2.nix"
  "/programs/gpu-screen-recorder.nix"
  "/programs/hamster.nix"
  "/programs/wayland/hyprlock.nix"
  "/programs/iay.nix"
  "/programs/iio-hyprland.nix"
  "/programs/immersed.nix"
  "/programs/wayland/labwc.nix"
  "/programs/lazygit.nix"
  "/programs/localsend.nix"
  "/programs/mepo.nix"
  "/programs/minipro.nix"
  "/programs/miriway.nix"
  "/programs/msmtp.nix"
  "/programs/nautilus-open-any-terminal.nix"
  "/programs/nethoscope.nix"
  "/programs/wayland/niri.nix"
  "/programs/nix-ld.nix"
  "/programs/nix-required-mounts.nix"
  "/programs/nm-applet.nix"
  "/programs/nncp.nix"
  "/programs/ns-usbloader.nix"
  "/programs/obs-studio.nix"
  "/programs/oddjobd.nix"
  "/programs/opengamepadui.nix"
  "/programs/openvpn3.nix"
  "/programs/partition-manager.nix"
  "/programs/pay-respects.nix"
  "/programs/plotinus.nix"
  "/programs/pqos-wrapper.nix"
  "/programs/projecteur.nix"
  "/programs/proxychains.nix"
  "/programs/qdmr.nix"
  "/programs/qgroundcontrol.nix"
  "/programs/quark-goldleaf.nix"
  "/programs/wayland/river.nix"
  "/programs/rog-control-center.nix"
  "/programs/rust-motd.nix"
  "/programs/ryzen-monitor-ng.nix"
  "/programs/sniffnet.nix"
  "/programs/starship.nix"
  "/programs/steam.nix"
  "/programs/streamcontroller.nix"
  "/programs/streamdeck-ui.nix"
  "/programs/wayland/sway.nix"
  "/programs/thunar.nix"
  "/programs/thunderbird.nix"
  "/programs/tmux.nix"
  "/programs/trippy.nix"
  "/programs/tsm-client.nix"
  "/programs/wayland/uwsm.nix"
  "/programs/vivid.nix"
  "/programs/wayland/waybar.nix"
  "/programs/wayland/wayfire.nix"
  "/programs/wayland/miracle-wm.nix"
  "/programs/wshowkeys.nix"
  "/programs/xastir.nix"
  "/programs/xfconf.nix"
  "/programs/yazi.nix"
  "/programs/ydotool.nix"
  "/programs/zsh/oh-my-zsh.nix"
  "/config/qt.nix"
  "/security/misc.nix"
  "/security/audit.nix"
  "/security/dhparams.nix"
  "/security/doas.nix"
  "/security/lock-kernel-modules.nix"
  [ "/security/pam_mount.nix" ]
  [ "/security/oath.nix" ]
  "/services/display-managers/greetd.nix"
  "/security/soteria.nix"
  "/security/sudo-rs.nix"
  "/security/tpm2.nix"
  "/services/networking/3proxy.nix"
  "/services/desktops/accountsservice.nix"
  "/services/web-apps/actual.nix"
  "/services/web-apps/akkoma.nix"
  "/services/monitoring/alloy.nix"
  "/services/misc/ananicy.nix"
  "/services/misc/anki-sync-server.nix"
  "/services/web-apps/anuko-time-tracker.nix"
  "/services/monitoring/arbtt.nix"
  "/services/games/archisteamfarm.nix"
  "/services/web-apps/archtika.nix"
  "/services/web-apps/artalk.nix"
  "/services/development/athens.nix"
  "/services/web-apps/audiobookshelf.nix"
  "/services/hardware/auto-cpufreq.nix"
  "/services/hardware/auto-epp.nix"
  "/services/misc/autorandr.nix"
  "/services/misc/autosuspend.nix"
  [ "/services/networking/avahi-daemon.nix" ]
  "/services/desktops/ayatana-indicators.nix"
  "/services/networking/babeld.nix"
  "/services/desktops/bamf.nix"
  "/services/networking/bee.nix"
  "/services/misc/bees.nix"
  "/services/monitoring/below.nix"
  "/services/networking/biboumi.nix"
  "/services/networking/bird-lg.nix"
  "/services/networking/bitcoind.nix"
  "/services/torrent/bitmagnet.nix"
  "/services/security/bitwarden-directory-connector-cli.nix"
  "/services/development/blackfire.nix"
  "/services/misc/blenderfarm.nix"
  "/services/networking/blockbook-frontend.nix"
  "/services/web-apps/bluemap.nix"
  "/services/computing/boinc/client.nix"
  "/services/desktops/bonsaid.nix"
  "/services/backup/borgbackup.nix"
  "/services/audio/botamusique.nix"
  "/services/system/bpftune.nix"
  "/services/backup/btrbk.nix"
  "/services/hardware/buffyboard.nix"
  "/services/continuous-integration/buildbot/worker.nix"
  "/services/continuous-integration/buildkite-agents.nix"
  "/services/web-apps/c2fmzq-server.nix"
  "/services/system/cachix-agent/default.nix"
  "/services/system/cachix-watch-store.nix"
  "/services/monitoring/cadvisor.nix"
  "/services/wayland/cage.nix"
  "/services/misc/calibre-server.nix"
  "/services/web-apps/calibre-web.nix"
  "/services/security/canaille.nix"
  "/services/databases/cassandra.nix"
  "/services/web-apps/castopod.nix"
  "/services/monitoring/certspotter.nix"
  "/services/networking/chisel-server.nix"
  "/services/databases/chromadb.nix"
  "/services/mail/clamsmtp.nix"
  "/services/system/cloud-init.nix"
  "/services/networking/cloudflare-warp.nix"
  "/services/networking/cloudflared.nix"
  "/services/web-apps/cloudlog.nix"
  "/services/monitoring/cockpit.nix"
  "/services/databases/cockroachdb.nix"
  "/services/web-apps/code-server.nix"
  "/services/web-apps/coder.nix"
  "/services/web-apps/collabora-online.nix"
  "/services/web-apps/commafeed.nix"
  "/services/matrix/conduwuit.nix"
  "/services/networking/connman.nix"
  "/services/security/vault-agent.nix"
  "/services/networking/corerad.nix"
  "/services/networking/crab-hole.nix"
  "/services/networking/create_ap.nix"
  "/services/networking/croc.nix"
  "/services/scheduling/cron.nix"
  "/services/networking/dae.nix"
  "/services/networking/dante.nix"
  "/services/web-apps/davis.nix"
  "/services/misc/db-rest.nix"
  "/services/desktops/deepin/app-services.nix"
  "/services/desktops/deepin/dde-api.nix"
  "/services/desktops/deepin/dde-daemon.nix"
  "/services/matrix/dendrite.nix"
  "/services/web-apps/dependency-track.nix"
  "/services/web-apps/dex.nix"
  "/services/databases/dgraph.nix"
  "/services/web-apps/discourse.nix"
  "/services/display-managers/ly.nix"
  "/services/mail/dkimproxy-out.nix"
  "/services/networking/dnscrypt-proxy2.nix"
  "/services/networking/dnsproxy.nix"
  "/services/networking/doh-proxy-rust.nix"
  "/services/networking/doh-server.nix"
  "/services/web-apps/dokuwiki.nix"
  "/services/misc/duckdns.nix"
  "/services/home-automation/ebusd.nix"
  "/services/web-apps/echoip.nix"
  "/hardware/network/eg25-manager.nix"
  "/services/web-apps/eintopf.nix"
  "/services/editors/emacs.nix"
  "/services/security/endlessh.nix"
  "/services/security/endlessh-go.nix"
  "/services/networking/epmd.nix"
  "/services/networking/ergochat.nix"
  "/services/network-filesystems/eris-server.nix"
  "/services/desktops/espanso.nix"
  "/services/home-automation/esphome.nix"
  "/services/networking/eternal-terminal.nix"
  "/services/home-automation/evcc.nix"
  "/services/networking/expressvpn.nix"
  "/services/networking/fakeroute.nix"
  "/services/networking/fastnetmon-advanced.nix"
  "/services/networking/fedimintd.nix"
  "/services/databases/ferretdb.nix"
  "/services/web-apps/fider.nix"
  "/services/web-apps/filesender.nix"
  "/services/networking/firefox-syncserver.nix"
  "/services/web-apps/flarum.nix"
  "/services/desktops/flatpak.nix"
  "/services/torrent/flood.nix"
  "/services/databases/foundationdb.nix"
  [ "/services/security/fprintd.nix" ]
  "/services/games/freeciv.nix"
  "/services/web-apps/freshrss.nix"
  "/services/video/frigate.nix"
  "/services/networking/frp.nix"
  "/services/misc/fstrim.nix"
  "/services/hardware/g810-led.nix"
  "/services/web-apps/galene.nix"
  "/services/web-servers/garage.nix"
  "/services/monitoring/gatus.nix"
  "/services/desktops/geoclue2.nix"
  "/services/web-apps/gerrit.nix"
  "/services/networking/ghostunnel.nix"
  "/services/continuous-integration/gitea-actions-runner.nix"
  "/services/monitoring/gitwatch.nix"
  "/services/web-apps/glance.nix"
  "/services/monitoring/glances.nix"
  "/services/desktops/gnome/glib-networking.nix"
  "/services/desktops/gnome/gnome-browser-connector.nix"
  "/services/desktops/gnome/gnome-initial-setup.nix"
  "/services/desktops/gnome/gnome-keyring.nix"
  "/services/desktops/gnome/gnome-online-accounts.nix"
  "/services/desktops/gnome/gnome-remote-desktop.nix"
  "/services/desktops/gnome/gnome-settings-daemon.nix"
  "/services/desktops/gnome/gnome-user-share.nix"
  "/services/desktops/gnome/localsearch.nix"
  "/services/desktops/gnome/rygel.nix"
  "/services/desktops/gnome/sushi.nix"
  "/services/networking/gns3-server.nix"
  "/services/networking/go-autoconfig.nix"
  "/services/networking/go-neb.nix"
  "/services/video/go2rtc/default.nix"
  "/services/web-apps/goatcounter.nix"
  "/services/mail/goeland.nix"
  "/services/audio/gonic.nix"
  "/services/monitoring/goss.nix"
  "/services/misc/gotenberg.nix"
  "/services/web-apps/gotify-server.nix"
  "/services/web-apps/gotosocial.nix"
  "/services/home-automation/govee2mqtt.nix"
  "/services/audio/goxlr-utility.nix"
  "/services/monitoring/grafana-agent.nix"
  "/services/monitoring/grafana-image-renderer.nix"
  "/services/web-apps/grocy.nix"
  "/services/desktops/gsignond.nix"
  "/services/misc/guix"
  "/services/desktops/gvfs.nix"
  "/services/hardware/handheld-daemon.nix"
  "/services/networking/hans.nix"
  "/services/hardware/argonone.nix"
  "/services/hardware/lcd.nix"
  "/services/hardware/openrgb.nix"
  "/services/web-apps/hatsu.nix"
  "/services/matrix/hebbot.nix"
  "/services/misc/heisenbridge.nix"
  "/services/networking/hickory-dns.nix"
  "/services/security/hockeypuck.nix"
  "/services/security/hologram-agent.nix"
  "/services/web-apps/homebox.nix"
  [ "/system/boot/systemd/homed.nix" ]
  "/services/web-apps/honk.nix"
  "/services/networking/https-dns-proxy.nix"
  "/services/networking/hylafax/options.nix"
  "/services/wayland/hypridle.nix"
  "/services/networking/icecream/daemon.nix"
  "/services/networking/icecream/scheduler.nix"
  "/services/web-apps/icingaweb2/icingaweb2.nix"
  "/services/web-apps/ifm.nix"
  "/services/networking/imaginary.nix"
  "/services/databases/influxdb2.nix"
  "/services/misc/input-remapper.nix"
  "/services/hardware/inputplumber.nix"
  "/services/networking/inspircd.nix"
  "/services/security/intune.nix"
  "/services/misc/invidious-router.nix"
  "/services/hardware/iptsd.nix"
  "/services/networking/ivpn.nix"
  "/services/audio/jack.nix"
  "/services/misc/jellyfin.nix"
  "/services/misc/jellyseerr.nix"
  "/services/networking/jibri/default.nix"
  "/services/networking/jicofo.nix"
  "/services/networking/jigasi.nix"
  "/services/web-apps/jirafeau.nix"
  "/services/web-apps/jitsi-meet.nix"
  "/services/security/jitterentropy-rngd.nix"
  "/services/audio/jmusicbot.nix"
  "/services/networking/jotta-cli.nix"
  "/system/boot/systemd/journald-gateway.nix"
  "/system/boot/systemd/journald-remote.nix"
  "/system/boot/systemd/journald-upload.nix"
  "/services/logging/journalwatch.nix"
  "/services/development/jupyter/default.nix"
  "/services/development/jupyterhub/default.nix"
  "/services/hardware/kanata.nix"
  "/services/web-apps/kanboard.nix"
  "/services/security/kanidm.nix"
  "/services/web-apps/kavita.nix"
  "/services/networking/kea.nix"
  "/services/networking/keepalived/default.nix"
  "/services/system/kerberos/default.nix"
  "/services/web-servers/keter"
  "/services/misc/klipper.nix"
  "/services/hardware/kmonad.nix"
  "/services/web-apps/komga.nix"
  "/services/cluster/kubernetes/addon-manager.nix"
  "/services/cluster/kubernetes/flannel.nix"
  "/services/cluster/kubernetes/pki.nix"
  "/services/cluster/kubernetes/proxy.nix"
  "/services/cluster/kubernetes/scheduler.nix"
  "/services/network-filesystems/kubo.nix"
  "/services/web-apps/lanraragi.nix"
  "/services/monitoring/librenms.nix"
  "/services/misc/lifecycled.nix"
  "/services/network-filesystems/litestream/default.nix"
  "/services/development/livebook.nix"
  "/services/misc/llama-cpp.nix"
  "/services/networking/magic-wormhole-mailbox-server.nix"
  "/services/torrent/magnetico.nix"
  "/services/mail/mailpit.nix"
  "/services/misc/mame.nix"
  "/services/search/manticore.nix"
  "/services/matrix/appservice-discord.nix"
  "/services/matrix/appservice-irc.nix"
  "/services/matrix/conduit.nix"
  "/services/matrix/hookshot.nix"
  "/services/home-automation/matter-server.nix"
  "/services/web-apps/mattermost.nix"
  "/services/matrix/maubot.nix"
  "/services/matrix/mautrix-meta.nix"
  "/services/matrix/mautrix-signal.nix"
  "/services/matrix/mautrix-telegram.nix"
  "/services/matrix/mautrix-whatsapp.nix"
  "/services/games/mchprs.nix"
  "/services/video/mediamtx.nix"
  "/services/search/meilisearch.nix"
  "/services/admin/meshcentral.nix"
  "/services/web-apps/microbin.nix"
  "/services/web-servers/mighttpd2.nix"
  "/services/networking/mihomo.nix"
  "/services/web-servers/minio.nix"
  "/services/web-apps/misskey.nix"
  "/services/matrix/mjolnir.nix"
  "/services/web-apps/mobilizon.nix"
  "/services/misc/mollysocket.nix"
  "/services/hardware/monado.nix"
  "/services/networking/monero.nix"
  "/services/databases/monetdb.nix"
  "/services/monitoring/monit.nix"
  "/services/misc/moonraker.nix"
  "/services/networking/mosquitto.nix"
  "/services/networking/mozillavpn.nix"
  "/services/networking/mptcpd.nix"
  "/services/networking/mullvad-vpn.nix"
  [ "/services/networking/multipath.nix" ]
  "/services/audio/music-assistant.nix"
  "/services/matrix/mx-puppet-discord.nix"
  "/services/networking/mycelium.nix"
  "/services/audio/mympd.nix"
  "/services/backup/mysql-backup.nix"
  "/services/networking/namecoind.nix"
  "/services/networking/nar-serve.nix"
  "/services/audio/navidrome.nix"
  "/services/networking/ncdns.nix"
  "/services/networking/ncps.nix"
  "/services/networking/nebula.nix"
  "/services/networking/netbird/coturn.nix"
  "/services/networking/netbird/server.nix"
  "/services/networking/netclient.nix"
  "/services/web-apps/nextcloud-whiteboard-server.nix"
  "/services/web-apps/nextjs-ollama-llm-ui.nix"
  "/services/web-apps/nexus.nix"
  "/services/monitoring/nezha-agent.nix"
  "/services/web-servers/nginx/gitweb.nix"
  "/services/web-servers/nginx/tailscale-auth.nix"
  "/services/networking/nix-store-gcs-proxy.nix"
  "/services/web-apps/nostr-rs-relay.nix"
  "/services/misc/novacomd.nix"
  "/services/networking/nsd.nix"
  "/services/networking/ntp/ntpd-rs.nix"
  "/services/web-apps/ocis.nix"
  "/services/monitoring/ocsinventory-agent.nix"
  "/services/web-apps/open-web-calendar.nix"
  "/services/misc/open-webui.nix"
  "/services/networking/opengfw.nix"
  "/services/databases/openldap.nix"
  "/services/security/opensnitch.nix"
  [ "/services/networking/ssh/sshd.nix" ]
  "/services/web-apps/openvscode-server.nix"
  "/services/misc/owncast.nix"
  "/services/matrix/pantalaimon.nix"
  "/services/misc/paperless.nix"
  "/services/monitoring/parsedmarc.nix"
  "/services/security/pass-secret-service.nix"
  "/services/web-apps/pds.nix"
  "/services/web-apps/peering-manager.nix"
  "/services/networking/peroxide.nix"
  "/services/misc/persistent-evdev.nix"
  "/services/web-apps/photoprism.nix"
  "/services/web-apps/phylactery.nix"
  "/services/web-apps/pict-rs.nix"
  "/services/web-apps/pingvin-share.nix"
  "/services/misc/pinnwand.nix"
  "/services/networking/pixiecore.nix"
  "/services/desktops/playerctld.nix"
  "/services/networking/pleroma.nix"
  "/services/misc/podgrab.nix"
  "/services/misc/polaris.nix"
  "/services/web-apps/porn-vault/default.nix"
  "/services/misc/portunus.nix"
  "/services/backup/postgresql-wal-receiver.nix"
  "/services/web-apps/powerdns-admin.nix"
  "/services/hardware/powerstation.nix"
  "/services/networking/pppd.nix"
  "/services/misc/preload.nix"
  "/services/web-apps/pretalx.nix"
  "/services/web-apps/pretix.nix"
  "/services/printing/cups-pdf.nix"
  "/services/misc/private-gpt.nix"
  "/services/monitoring/prometheus/alertmanager-gotify-bridge.nix"
  "/services/monitoring/prometheus/alertmanager-irc-relay.nix"
  "/services/monitoring/prometheus/alertmanager-webhook-logger.nix"
  "/services/networking/prosody.nix"
  "/services/mail/protonmail-bridge.nix"
  "/services/mail/public-inbox.nix"
  "/services/misc/pufferpanel.nix"
  [ "/services/audio/pulseaudio.nix" ]
  "/services/networking/pyload.nix"
  "/services/games/quake3-server.nix"
  "/services/networking/quicktun.nix"
  "/services/networking/radicale.nix"
  "/services/misc/radicle.nix"
  "/services/networking/rathole.nix"
  "/services/web-apps/readeck.nix"
  "/services/networking/realm.nix"
  "/services/misc/redlib.nix"
  "/services/networking/redsocks.nix"
  "/services/misc/renovate.nix"
  "/services/networking/resilio.nix"
  "/services/backup/restic-rest-server.nix"
  "/services/web-apps/rimgo.nix"
  "/services/misc/rkvm.nix"
  "/services/misc/rmfakecloud.nix"
  "/services/networking/routedns.nix"
  "/services/networking/routinator.nix"
  "/services/misc/rshim.nix"
  "/services/mail/rspamd-trainer.nix"
  "/services/web-apps/rss-bridge.nix"
  "/services/mail/rss2email.nix"
  "/services/development/rstudio-server/default.nix"
  [ "/services/logging/rsyslogd.nix" ]
  "/services/torrent/rtorrent.nix"
  "/services/web-servers/rustus.nix"
  "/services/admin/salt/master.nix"
  "/services/backup/sanoid.nix"
  "/services/web-apps/screego.nix"
  "/services/monitoring/scrutiny.nix"
  "/services/scheduling/scx.nix"
  "/services/networking/seafile.nix"
  "/services/networking/searx.nix"
  "/services/desktops/seatd.nix"
  "/services/web-servers/send.nix"
  "/services/security/shibboleth-sp.nix"
  "/services/web-apps/shiori.nix"
  "/services/web-apps/silverbullet.nix"
  "/services/networking/sing-box.nix"
  "/services/security/sks.nix"
  "/services/web-apps/slskd.nix"
  "/services/misc/snapper.nix"
  "/services/audio/snapserver.nix"
  "/services/web-apps/snipe-it.nix"
  "/services/monitoring/snmpd.nix"
  "/services/networking/snowflake-proxy.nix"
  "/services/misc/soft-serve.nix"
  "/services/networking/soju.nix"
  "/services/search/sonic-server.nix"
  "/services/audio/spotifyd.nix"
  "/services/security/sslmate-agent.nix"
  "/services/misc/sssd.nix"
  "/services/mail/stalwart-mail.nix"
  "/services/web-servers/stargazer.nix"
  "/services/web-apps/stash.nix"
  "/services/web-servers/static-web-server.nix"
  "/services/security/step-ca.nix"
  "/services/web-apps/stirling-pdf.nix"
  "/services/hardware/supergfxd.nix"
  "/services/networking/suricata/default.nix"
  "/services/web-apps/suwayomi-server.nix"
  "/services/system/swapspace.nix"
  "/services/mail/sympa.nix"
  "/services/backup/syncoid.nix"
  "/services/misc/sysprof.nix"
  "/services/desktops/system76-scheduler.nix"
  "/services/system/systemd-lock-handler.nix"
  "/services/networking/tailscale-derper.nix"
  "/services/networking/tailscale.nix"
  "/services/networking/tailscale-auth.nix"
  "/services/misc/tandoor-recipes.nix"
  "/services/security/tang.nix"
  "/services/networking/teamspeak3.nix"
  "/services/networking/technitium-dns-server.nix"
  "/services/desktops/telepathy.nix"
  "/services/databases/tigerbeetle.nix"
  "/services/search/tika.nix"
  "/services/networking/tinc.nix"
  "/services/networking/tinyproxy.nix"
  "/services/networking/tmate-ssh-server.nix"
  "/services/web-servers/tomcat.nix"
  "/services/x11/touchegg.nix"
  "/services/misc/tp-auto-kbbl.nix"
  "/services/misc/transfer-sh.nix"
  "/services/torrent/transmission.nix"
  "/services/hardware/trezord.nix"
  "/services/networking/trickster.nix"
  "/services/backup/tsm.nix"
  "/services/monitoring/tuptime.nix"
  "/services/misc/tzupdate.nix"
  "/services/hardware/usbmuxd.nix"
  "/services/x11/unclutter.nix"
  [ "/services/monitoring/unpoller.nix" ]
  "/services/monitoring/uptime-kuma.nix"
  "/services/x11/urxvtd.nix"
  "/services/hardware/usbrelayd.nix"
  "/services/system/userborn.nix"
  "/services/networking/v2raya.nix"
  "/services/video/v4l2-relayd.nix"
  "/services/security/vaultwarden/default.nix"
  "/services/networking/veilid.nix"
  "/services/monitoring/vnstat.nix"
  "/services/development/vsmartcard-vpcd.nix"
  "/services/web-apps/wakapi.nix"
  "/services/misc/wastebin.nix"
  "/services/monitoring/watchdogd.nix"
  "/services/network-filesystems/webdav.nix"
  "/services/network-filesystems/webdav-server-rs.nix"
  "/services/web-apps/weblate.nix"
  "/services/misc/weechat.nix"
  "/services/networking/wg-netmanager.nix"
  "/services/web-apps/wiki-js.nix"
  "/services/video/wivrn.nix"
  "/services/continuous-integration/woodpecker/agents.nix"
  "/services/continuous-integration/woodpecker/server.nix"
  "/services/misc/workout-tracker.nix"
  "/services/networking/wstunnel.nix"
  "/services/home-automation/wyoming/satellite.nix"
  "/services/misc/xmrig.nix"
  "/services/games/xonotic.nix"
  "/services/x11/xscreensaver.nix"
  "/services/x11/desktop-managers/none.nix"
  "/services/x11/desktop-managers/default.nix"
  "/services/x11/display-managers/lightdm.nix"
  "/services/x11/window-managers/default.nix"
  "/services/x11/display-managers/sx.nix"
  [ "/services/x11/display-managers/xpra.nix" ]
  "/services/x11/window-managers/none.nix"
  "/services/x11/window-managers/xmonad.nix"
  "/services/networking/yggdrasil.nix"
  "/services/networking/yggdrasil-jumper.nix"
  "/services/web-apps/your_spotify.nix"
  "/services/misc/ytdl-sub.nix"
  "/services/security/yubikey-agent.nix"
  "/services/development/zammad.nix"
  "/services/networking/zapret.nix"
  "/services/desktops/zeitgeist.nix"
  "/services/backup/zfs-replication.nix"
  "/services/web-apps/zipline.nix"
  "/services/web-apps/zitadel.nix"
  "/services/backup/znapzend.nix"
  "/services/misc/zoneminder.nix"
  "/services/system/zram-generator.nix"
  "/services/backup/zrepl.nix"
  "/services/home-automation/zwave-js.nix"
  "/services/home-automation/zwave-js-ui.nix"
  "/system/activation/specialisation.nix"
  "/system/activation/activatable-system.nix"
  "/system/activation/switchable-system.nix"
  "/system/etc/etc-activation.nix"
  "/virtualisation/build-vm.nix"
  "/system/boot/uki.nix"
  "/image/images.nix"
  "/system/build.nix"
  "/tasks/filesystems/vfat.nix"
  "/misc/label.nix"
  [ "/system/activation/pre-switch-check.nix" ]
  "/system/boot/systemd/tpm2.nix"
  "/system/boot/emergency-mode.nix"
  "/system/boot/systemd/shutdown.nix"
  "/system/boot/systemd/nspawn.nix"
  [ "/testing/service-runner.nix" ]
  "/system/boot/systemd/sysupdate.nix"
  "/system/boot/systemd/sysusers.nix"
  [ "/config/ldap.nix" ]
  "/config/mysql.nix"
  "/virtualisation/containers.nix"
  "/virtualisation/cri-o.nix"
  "/virtualisation/incus-agent.nix"
  "/virtualisation/incus.nix"
  "/virtualisation/kvmgt.nix"
  "/virtualisation/lxc.nix"
  "/virtualisation/lxcfs.nix"
  "/virtualisation/vmware-guest.nix"
  "/services/x11/window-managers/fvwm2.nix"
  "/services/x11/desktop-managers/enlightenment.nix"
  "/services/desktop-managers/plasma6.nix"
  [ "/virtualisation/virtualbox-guest.nix" ]
  [ "/virtualisation/oci-options.nix" ]
  [ "/virtualisation/oci-containers.nix" ]
  [ "/tasks/swraid.nix" ]
  [ "/system/boot/grow-partition.nix" ]
  [ "/services/x11/redshift.nix" ]
  [ "/services/x11/extra-layouts.nix" ]
  [ "/services/web-apps/zabbix.nix" ]
  [ "/services/web-apps/mediawiki.nix" ]
  [ "/services/web-apps/engelsystem.nix" ]
  [ "/services/system/localtimed.nix" ]
  [ "/services/security/oauth2-proxy.nix" ]
  [ "/services/networking/x2goserver.nix" ]
  [ "/services/networking/spacecookie.nix" ]
  [ "/services/networking/ntopng.nix" ]
  [ "/services/networking/knot.nix" ]
  [ "/services/networking/i2pd.nix" ]
  [ "/services/network-filesystems/nfsd.nix" ]
  [ "/services/monitoring/prometheus/xmpp-alerts.nix" ]
  [ "/services/misc/tautulli.nix" ]
  [ "/services/misc/mbpfan.nix" ]
  [ "/services/misc/dysnomia.nix" ]
  [ "/services/misc/amazon-ssm-agent.nix" ]
  [ "/services/mail/postgrey.nix" ]
  [ "/services/mail/opensmtpd.nix" ]
  [ "/services/mail/opendkim.nix" ]
  [ "/services/hardware/pcscd.nix" ]
  [ "/services/hardware/nvidia-container-toolkit" ]
  [ "/services/hardware/libinput.nix" ]
  [ "/services/databases/hbase-standalone.nix" ]
  "/services/continuous-integration/hercules-ci-agent/default.nix"
  [ "/services/backup/snapraid.nix" ]
  [ "/services/backup/automysqlbackup.nix" ]
  [ "/security/chromium-suid-sandbox.nix" ]
  [ "/programs/zsh/zsh-syntax-highlighting.nix" ]
  [ "/programs/zsh/zsh-autosuggestions.nix" ]
  [ "/programs/gdk-pixbuf.nix" ]
  "/i18n/input-method/ibus.nix"
  [ "/hardware/usb-storage.nix" ]
  [ "/hardware/usb-modeswitch.nix" ]
  [ "/hardware/tuxedo-drivers.nix" ]
  [ "/hardware/logitech.nix" ]
  [ "/hardware/ksm.nix" ]
  "/config/xdg/portals/lxqt.nix"
  "/config/xdg/portals/wlr.nix"
  "/config/xdg/terminal-exec.nix"
]
